"""
事件系统模块

提供事件驱动架构的核心组件，包括事件总线、事件定义和事件处理器。

模块结构：
- types.py: 事件类型定义
- event_bus.py: 事件总线
- aggregators.py: 事件聚合器
- realtime_write_events.py: 数据写入相关事件
"""

from .event_bus import EventBus, get_event_bus

EVENT_BUS_AVAILABLE = True

from .types import (
    BaseEvent,
    EventPriority,
    EventType,
    EventFilter,
    AssetSelectedEvent,
    StockSelectedEvent,
    AssetDataReadyEvent,
    UIDataReadyEvent,
    ChartUpdateEvent,
    AnalysisCompleteEvent,
    DataUpdateEvent,
    ErrorEvent,
    UIUpdateEvent,
    ThemeChangedEvent,
    PerformanceUpdateEvent,
    IndicatorChangedEvent,
    MultiScreenToggleEvent,
    TradeExecutedEvent,
    PositionUpdatedEvent,
    PatternSignalsDisplayEvent,
    AlertLevel,
    ResourceAlert,
    ApplicationAlert,
    RealtimeDataEvent,
    TickDataEvent,
    OrderBookEvent,
    ComputedIndicatorEvent,
    StrategyStartedEvent,
    StrategyStoppedEvent,
    StrategyPausedEvent,
    StrategyResumedEvent,
    StrategyErrorEvent,
    SignalGeneratedEvent,
    PerformanceUpdatedEvent,
    DataIntegrityEvent,
    DataAnalysisEvent,
    UpdateHistoryEvent,
    TrainingTaskCreatedEvent,
    TrainingTaskStatusChangedEvent,
    TrainingProgressUpdatedEvent,
    ModelVersionCreatedEvent,
    ModelVersionCurrentChangedEvent,
    ModelVersionRolledBackEvent,
    PredictionRecordedEvent,
    PredictionAccuracyUpdatedEvent,
    StrategyConfigCreatedEvent,
    StrategyConfigUpdatedEvent,
    StrategyConfigDeletedEvent,
    StrategyConfigsLoadedEvent,
    Event,
)
from .event_handler import EventHandler, AsyncEventHandler
from .aggregators import (
    AggregationStrategy,
    AggregationConfig,
    AggregatedResult,
    BaseAggregator,
    EventAggregator,
    SignalAggregator,
    MarketDataAggregator,
    AggregationManager,
)
from .realtime_write_events import (
    WriteStartedEvent,
    WriteProgressEvent,
    WriteCompletedEvent,
    WriteErrorEvent,
)

__all__ = [
    'EventBus',
    'get_event_bus',
    'EVENT_BUS_AVAILABLE',
    'EventHandler',
    'AsyncEventHandler',
    'BaseEvent',
    'EventPriority',
    'EventType',
    'EventFilter',
    'AssetSelectedEvent',
    'StockSelectedEvent',
    'AssetDataReadyEvent',
    'UIDataReadyEvent',
    'ChartUpdateEvent',
    'AnalysisCompleteEvent',
    'DataUpdateEvent',
    'ErrorEvent',
    'UIUpdateEvent',
    'ThemeChangedEvent',
    'PerformanceUpdateEvent',
    'IndicatorChangedEvent',
    'MultiScreenToggleEvent',
    'TradeExecutedEvent',
    'PositionUpdatedEvent',
    'PatternSignalsDisplayEvent',
    'AlertLevel',
    'ResourceAlert',
    'ApplicationAlert',
    'RealtimeDataEvent',
    'TickDataEvent',
    'OrderBookEvent',
    'ComputedIndicatorEvent',
    'StrategyStartedEvent',
    'StrategyStoppedEvent',
    'StrategyPausedEvent',
    'StrategyResumedEvent',
    'StrategyErrorEvent',
    'SignalGeneratedEvent',
    'PerformanceUpdatedEvent',
    'DataIntegrityEvent',
    'DataAnalysisEvent',
    'UpdateHistoryEvent',
    'TrainingTaskCreatedEvent',
    'TrainingTaskStatusChangedEvent',
    'TrainingProgressUpdatedEvent',
    'ModelVersionCreatedEvent',
    'ModelVersionCurrentChangedEvent',
    'ModelVersionRolledBackEvent',
    'PredictionRecordedEvent',
    'PredictionAccuracyUpdatedEvent',
    'StrategyConfigCreatedEvent',
    'StrategyConfigUpdatedEvent',
    'StrategyConfigDeletedEvent',
    'StrategyConfigsLoadedEvent',
    'AggregationStrategy',
    'AggregationConfig',
    'AggregatedResult',
    'BaseAggregator',
    'EventAggregator',
    'SignalAggregator',
    'MarketDataAggregator',
    'AggregationManager',
    'WriteStartedEvent',
    'WriteProgressEvent',
    'WriteCompletedEvent',
    'WriteErrorEvent',
    'Event',
]
