"""R168-A key services dead code check (5+1 services + key services)"""
import os
import re
from pathlib import Path

# Check several key files for unused methods / classes
KEY_SERVICES = [
    "core/services/risk_manager.py",  # 5+1
    "core/services/trading_service.py",  # 5+1
    "core/trading/account_manager.py",  # 5+1 (in core/trading not core/services!)
    "core/money_manager.py",  # 5+1
    "core/risk_control.py",  # 5+1
    "core/services/plugin_service.py",
    "core/services/ai_prediction_service.py",
    "core/services/ai_explainability_service.py",
    "core/services/auto_ml_optimizer.py",
    "core/services/ai_selection_backtest_service.py",
    "core/services/ai_selection_integration_service.py",
    "core/services/ai_selection_risk_control_service.py",
    "core/services/ai_stock_selector_service.py",
    "core/services/alert_deduplication_service.py",
    "core/services/alert_event_handler.py",
    "core/services/alert_rule_engine.py",
    "core/services/alert_rule_hot_loader.py",
    "core/services/bettafish_monitoring_service.py",
    "core/services/bettafish_advanced_monitoring_service.py",
    "core/services/bettafish_monitoring_integration.py",
    "core/services/data_masking_service.py",
    "core/services/audit_dead_code_service.py",
    "core/services/auto_training_pipeline.py",
    "core/services/backtest_result_manager.py",
    "core/services/distributed_service.py",
    "core/services/distributed_http_bridge.py",
    "core/services/deep_analysis_service.py",
    "core/services/feature_control_service.py",
    "core/services/funding_rate_analysis_service.py",
    "core/services/fundamental_data_manager.py",
    "core/services/gpu_acceleration_manager.py",
    "core/services/hybrid_recommendation_engine.py",
    "core/services/indicator_dependency_manager.py",
    "core/services/integrated_signal_aggregator_service.py",
    "core/services/macro_economic_data_manager.py",
    "core/services/llm_config_service.py",
    "core/services/lifecycle_service.py",
    "core/services/market_cap_calculator.py",
    "core/services/notification_service.py",
    "core/services/performance_baseline_service.py",
    "core/services/performance_data_bridge.py",
    "core/services/quality_report_generator.py",
    "core/services/realtime_compute_engine.py",
    "core/services/recommendation_explanation_generator.py",
    "core/services/sector_data_service.py",
    "core/services/sector_fund_flow_service.py",
    "core/services/smart_recommendation_engine.py",
    "core/services/streaming_feature_engine.py",
    "core/services/strategy_status_monitor.py",
    "core/services/tdx_server_discovery.py",
    "core/services/tensorflow_gpu_manager.py",
    "core/services/trading_confirmation_service.py",
    "core/services/training_data_collector.py",
    "core/services/unified_cache_provider.py",
    "core/services/unified_chart_service.py",
    "core/services/unified_data_quality_monitor.py",
    "core/services/uni_plugin_data_manager.py",
    "core/services/asset_fallback_loader.py",
    "core/services/announcement_parser.py",
    "core/services/error_handling_service.py",
    "core/services/extension_service.py",
    "core/services/database_monitoring_service.py",
    "core/services/dividend_data_service.py",
    "core/services/data_completeness_checker.py",
    "core/services/environment_service.py",
    "core/services/incremental_data_analyzer.py",
    "core/services/incremental_update_recorder.py",
    "core/services/incremental_update_scheduler.py",
    "core/services/fault_tolerance_manager.py",
    "core/services/fund_service.py",
    "core/services/bond_service.py",
    "core/services/index_service.py",
    "core/services/industry_service.py",
    "core/services/stock_service.py",
    "core/services/market_service.py",
    "core/services/cache_service.py",
    "core/services/data_service.py",
    "core/services/chart_service.py",
    "core/services/config_service.py",
    "core/services/database_service.py",
    "core/services/enhanced_data_manager.py",
    "core/services/enhanced_data_quality_monitor.py",
    "core/services/enhanced_duckdb_data_downloader.py",
    "core/services/enhanced_performance_bridge.py",
    "core/services/enhanced_realtime_data_manager.py",
    "core/services/analysis_service.py",
    "core/services/notification_service.py",
    "core/services/notification_service.py",
    "core/services/network_service.py",
    "core/services/security_service.py",
    "core/services/signal_trading_bridge.py",
    "core/services/strategy_service.py",
    "core/services/strategy_plugin_pool.py",
    "core/services/performance_service.py",
    "core/services/dynamic_risk_adjustment_service.py",
    "core/services/model_explainer.py",
    "core/services/model_training_service.py",
    "core/services/prediction_tracking_service.py",
    "core/services/recommendation_model_trainer.py",
    "core/services/progress_persistence_manager.py",
    "core/services/external_alert_channels_service.py",
    "core/services/external_alert_config_persistence.py",
    "core/services/scheduled_task_executor.py",
    "core/services/task_scheduler.py",
    "core/services/system_optimizer.py",
    "core/services/new_stock_fetcher.py",
    "core/services/deep_analysis_framework.py",
    "core/services/dependency_resolver.py",
    "core/services/plugin_database_service.py",
    "core/services/unified_data_manager.py",
    "core/services/asset_service.py",
    "core/services/unified_plugin_service.py",
    "core/services/advanced_risk_control_service.py",
    "core/services/legacy_datasource_adapter.py",
    "core/services/singleton_protection.py",
    "core/plugin_hot_reloader.py",  # HVD-166-K2 candidate
    "core/plugin_version_manager.py",  # HVD-166-K2 candidate
    "core/services/db_utils.py",
    "core/services/metrics_base.py",
    "core/services/async_plugin_discovery.py",
    "core/services/distributed_http_bridge.py",
    "core/services/service_bootstrap.py",
    "core/services/service_health_monitor.py",
    "core/services/__init__.py",
    "core/services/base_service.py",
    "core/services/distributed_service.py",
]

for fp in KEY_SERVICES:
    if not os.path.exists(fp):
        continue
    with open(fp, 'r', encoding='utf-8') as f:
        content = f.read()
    classes = re.findall(r'^class\s+(\w+)\s*\(', content, re.MULTILINE)
    if not classes:
        continue
    size = os.path.getsize(fp)
    line_count = content.count('\n') + 1
    print(f"{fp} (lines={line_count}, size={size}B) classes={classes}")
